# check manuals
# https://github.com/RealSelf/dbt-source/blob/development/sample.profiles.yml
#



superstore:
  target: dev

  outputs:

    dev:
      dbname: superstore_db
      host: 172.23.174.10
      pass: pgpass123
      port: 5432
      schema: stg
      threads: 1
      type: postgres
      user: pguser1

    prod:
      dbname: superstore_db
      host: 172.23.174.10
      pass: pgpass123
      port: 5432
      schema: prod
      threads: 1
      type: postgres
      user: pguser1

# elite_production:
#   target: test

#   outputs:

#     test:
#       dbname: superstore_db
#       host: 172.23.174.10
#       pass: pgpass123
#       port: 5432
#       schema: test
#       threads: 1
#       type: postgres
#       user: pguser1

#     prod:
#       dbname: superstore_db
#       host: 172.23.174.10
#       pass: pgpass123
#       port: 5432
#       schema: marts
#       threads: 1
#       type: postgres
#       user: pguser1


